/*
 * Copyright (c) 2008 Xilinx, Inc.  All rights reserved.
 *
 * Xilinx, Inc.
 * XILINX IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS" AS A
 * COURTESY TO YOU.  BY PROVIDING THIS DESIGN, CODE, OR INFORMATION AS
 * ONE POSSIBLE   IMPLEMENTATION OF THIS FEATURE, APPLICATION OR
 * STANDARD, XILINX IS MAKING NO REPRESENTATION THAT THIS IMPLEMENTATION
 * IS FREE FROM ANY CLAIMS OF INFRINGEMENT, AND YOU ARE RESPONSIBLE
 * FOR OBTAINING ANY RIGHTS YOU MAY REQUIRE FOR YOUR IMPLEMENTATION.
 * XILINX EXPRESSLY DISCLAIMS ANY WARRANTY WHATSOEVER WITH RESPECT TO
 * THE ADEQUACY OF THE IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO
 * ANY WARRANTIES OR REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE
 * FROM CLAIMS OF INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

#ifndef _Pattern0_Setup_DUT_H_
#define _Pattern0_Setup_DUT_H_

#define XPAR_AXI_GPIO_dut0_1_BASEADDR	XPAR_AXI_GPIO_1_BASEADDR
#define XPAR_AXI_GPIO_dut1_1_BASEADDR	XPAR_AXI_GPIO_DUT1_1_BASEADDR
#define XPAR_AXI_GPIO_dut2_1_BASEADDR	XPAR_AXI_GPIO_DUT2_1_BASEADDR
#define XPAR_AXI_GPIO_dut3_1_BASEADDR	XPAR_AXI_GPIO_DUT3_1_BASEADDR

u8 _by_Pattern0_Setup_dut0();
u8 _by_Pattern0_Setup_dut1();
u8 _by_Pattern0_Setup_dut2();
u8 _by_Pattern0_Setup_dut3();

#endif
